# Generated by Django 3.2.7 on 2021-09-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('line', 'Line feature'), ('point', 'Point feature'), ('polygon', 'Polygon feature')], default='None', max_length=50)),
                ('link_to_file', models.FileField(upload_to='.')),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_link', models.FileField(upload_to='.')),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
        ),
    ]
